### ISSUE TITLE
Make all page data available on Webhook

### ISSUE THREAD

**Issue by mheiber** [clay/amphora#414] opened 2017-06-13 20:54 UTC
Right now, we have to do the following to get all page data from the "publish" webhook:

- iterate through all the refs in the payload and request each individually

This is awkward. Is there a better way? If not, I can think of two options:

- Send all the page data in the webhook payload. That is, send the data that is available when the page is requested using `.json` OR
- Send the page's uri (not just the vanity uri) in the payload. Happy to PR for this.

**Comment by jonwinton** [comment] 2017-06-18 20:32
Duplicate of #404. 

This would be a breaking change and can be added to the Amphora 4.0 release

**Comment by mheiber** [comment] 2017-06-21 14:20
@jonwinton not a duplicate, the solutions above would not be breaking changes. That said, I think we're OK to wait for #404 👍

**Comment by jonwinton** [comment] 2017-07-12 23:07
Sorry, should have explained. Your first solution is a byproduct of what #404 is proposing. If you're only sent the page uri then you can just request the page.json route and get all the data. Amphora should minimize the data sent over the wire since it can easily be re-requested by any service.

You can actually get the page uri from the vanity url if you base64 encode the vanity url and then request that from the `/uris` endpoint. It's a bit slower for now but would future-proof you for when #404  is done.

**Comment by mheiber** [comment] 2017-08-04 17:59
Another alternative: using an Amphora plugin instead of a web hook: https://github.com/clay/amphora/tree/master/lib/plugins  
The advantage is that any data at all that we want from Amphora could be easily-gotten via plugin handler methods like `save`.

cc @felkerch

**Closed** 2017-12-04 20:36 UTC
Labels: duplicate
