### ISSUE TITLE
Errors during component bootstrapping are caught but not reported

### ISSUE THREAD

**Issue by byronhulcher** [clay/amphora#435] opened 2017-09-25 14:37 UTC
https://github.com/clay/amphora/blob/821114ccbbecb1626c45d0a25a23434caf24a997/lib/bootstrap.js#L261
(ꐦ ಠ皿ಠ )

Ran into an issue where a component's model.js was throwing an error during the bootstrap phase, but since the error was caught silently, I had no idea!  Ideally this would log a message indicating the site, component, and include a traceback.

**Comment by nelsonpecora** [comment] 2017-09-25 14:47
@jonwinton I _think_ this error is the root cause of the issues with bootstrapping default component data, since the `locals` might not be passed in. Component `model.save`s that fail would result in 404ing default data, with no error logs.

**Comment by nelsonpecora** [comment] 2017-09-25 14:49
Also, we should update the bootstrap service anyway to account for users... https://github.com/clay/amphora/issues/360

**Comment by jonwinton** [comment] 2017-09-25 14:58
Yes! I'll move this into the v5 work

**Comment by jonwinton** [comment] 2017-10-06 17:07
Resolved in https://github.com/clay/amphora/pull/446

**Closed** 2017-10-06 17:08 UTC
Labels: bug, resolved
